updates:
- package-ecosystem: "github-actions"
  directory: "/"
    schedule:
      interval: "daily"
- package-ecosystem: "docker"
  directory: "/"
  registries:
    - dockerhub
  schedule:
    interval: "daily"
- package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
