version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - dockerhub
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
